# composite action, not to be run on its own, but included at the beginning of a build script

name: 'Setup the build environment'
description: 'Clones the required repositories, and properly sets Python and conan up'

inputs:
  conan_user:
    required: true
    type: string
  conan_password:
    required: true
    type: string
  private_data:
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Checkout Cura-workflows repo
      uses: actions/checkout@v4
      with:
        repository: Ultimaker/Cura-workflows
# FIXME: use main once merged
        ref: CURA-11622_conan_v2
        path: Cura-workflows

    - name: Setup Python and pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python requirements and setup Conan environment
# FIXME: use runner.os/runner.arch after merge: conan config install https://github.com/Ultimaker/conan-config.git -a "-b runner/runner.os/runner.arch"
      shell: bash
      run: |
        pip install -r Cura-workflows/.github/workflows/requirements-runner.txt

        conan profile detect -f
        conan config install https://github.com/Ultimaker/conan-config.git -a "-b CURA-11622_conan_v2"
        conan remote login cura-conan2 ${{ inputs.conan_user }} -p ${{ inputs.conan_password }}

        if [ "${{ inputs.private_data }}" == "true" ]; then
          conan remote enable cura-private-conan2
          conan remote login cura-private-conan2 ${{ inputs.conan_user }} -p ${{ inputs.conan_password }}
        fi
