name: Export Conan Recipe to server

on:
  workflow_call:
    inputs:
      recipe_id_name:
        required: true
        type: string

      recipe_id_version:
        required: true
        type: string

      recipe_id_user:
        required: true
        type: string

      recipe_id_channel:
        required: true
        type: string

      recipe_id_full:
        required: true
        type: string

      conan_internal:
        required: false
        default: false
        type: boolean

      conan_extra_args:
        required: false
        default: ""
        type: string

permissions:
  contents: read

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASS }}
  SENTRY_TOKEN: ${{ secrets.CURAENGINE_SENTRY_TOKEN }}

jobs:
  package-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Checkout repo PR
        uses: actions/checkout@v4
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        with:
          fetch-depth: 1
          ref: ${{ github.base_ref }}

      - name: Checkout Cura-workflows repo
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/Cura-workflows
# FIXME: use main once merged
          ref: CURA-11622_conan_v2
          path: Cura-workflows

      - name: Setup Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: Cura-workflows/.github/workflows/requirements-runner.txt

      - name: Install Python requirements and setup Conan environment
# FIXME: use runner.os/runner.arch after merge: conan config install https://github.com/Ultimaker/conan-config.git -a "-b runner/runner.os/runner.arch"
        run: |
          pip install -r actions/setup-python/.github/workflows/requirements-runner.txt

          conan profile detect -f
          conan config install https://github.com/Ultimaker/conan-config.git -a "-b CURA-11622_conan_v2"
          conan remote login -p ${{ secrets.CONAN_PASS }} cura-conan2 ${{ secrets.CONAN_USER }}

      - name: Add Cura private Artifactory remote
        if: ${{ inputs.conan_internal }}
        run: |
          conan remote enable cura-private-conan2
          conan remote login cura-private-conan2 ${{ secrets.CONAN_USER }} -p ${{ secrets.CONAN_PASS }}

      - name: Export the Package
        run: conan export . --name ${{ inputs.recipe_id_name }} --version ${{ inputs.recipe_id_version }} --user ${{ inputs.recipe_id_user }} --channel ${{ inputs.recipe_id_channel }} ${{ inputs.conan_extra_args }}

      - name: Upload the Package(s)
        if: ${{ !inputs.conan_internal}}
        run: |
          conan upload ${{ inputs.recipe_id_full }} -r cura-conan2 -c

      - name: Upload the Package(s) to the private Artifactory
        if: ${{ inputs.conan_internal }}
        run: |
          conan upload ${{ inputs.recipe_id_full }} -r cura-private-conan2 -c
