name: Export Conan Recipe to server

on:
  workflow_call:
    inputs:
      recipe_id_name:
        required: true
        type: string

      recipe_id_version:
        required: true
        type: string

      recipe_id_user:
        required: true
        type: string

      recipe_id_channel:
        required: true
        type: string

      recipe_id_full:
        required: true
        type: string

      conan_internal:
        required: false
        default: false
        type: boolean

      conan_extra_args:
        required: false
        default: ""
        type: string

      conan_recipe_root:
        required: false
        default: "."
        type: string

permissions:
  contents: read

jobs:
  package-export:
    runs-on: ubuntu-latest

    steps:
# FIXME: use main once merged
      - uses: ultimaker/cura-workflows/.github/actions/setup-build-environment.yml@CURA-11622_conan_v2
        with:
          conan_user: ${{ secrets.CONAN_USER }}
          conan_password: ${{ secrets.CONAN_PASS }}

      - name: Export the Package
        run: conan export ${{ inputs.conan_recipe_root }} --name ${{ inputs.recipe_id_name }} --version ${{ inputs.recipe_id_version }} --user ${{ inputs.recipe_id_user }} --channel ${{ inputs.recipe_id_channel }} ${{ inputs.conan_extra_args }}

      - name: Upload the Package(s)
        if: ${{ !inputs.conan_internal}}
        run: |
          conan upload ${{ inputs.recipe_id_full }} -r cura-conan2 -c

      - name: Upload the Package(s) to the private Artifactory
        if: ${{ inputs.conan_internal }}
        run: |
          conan upload ${{ inputs.recipe_id_full }} -r cura-private-conan2 -c
