name: Conan package create Windows

on:
  workflow_call:
    inputs:
      recipe_id_name:
        required: true
        type: string

      recipe_id_version:
        required: true
        type: string

      recipe_id_user:
        required: true
        type: string

      recipe_id_channel:
        required: true
        type: string

      recipe_id_full:
        required: true
        type: string

      conan_internal:
        required: false
        default: false
        type: boolean

      conan_extra_args:
        required: false
        default: ""
        type: string

      conan_recipe_root:
        required: false
        default: "."
        type: string

permissions:
  contents: read

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASS }}
  SENTRY_TOKEN: ${{ secrets.CURAENGINE_SENTRY_TOKEN }}

jobs:
  package-create:
    runs-on: windows-2022

    steps:
# FIXME: use main once merged
      - name: Setup the build environment
        uses: ultimaker/cura-workflows/.github/actions/setup-build-environment@CURA-11622_conan_v2
        with:
          conan_user: ${{ secrets.CONAN_USER }}
          conan_password: ${{ secrets.CONAN_PASS }}
          install_system_depndencies: true

      - name: Create the Package (binaries)
        shell: cmd
        run: conan create ${{ inputs.conan_recipe_root }} --name ${{ inputs.recipe_id_name }} --version ${{ inputs.recipe_id_version }} --user ${{ inputs.recipe_id_user }} --channel ${{ inputs.recipe_id_channel }} ${{ inputs.conan_extra_args }} --build=missing

# FIXME: use main once merged
      - name: Upload the Packages
        uses: ultimaker/cura-workflows/.github/actions/upload-conan-package@CURA-11622_conan_v2
        with:
          package_name: ${{ inputs.recipe_id_full }}
          private_data: ${{ inputs.conan_internal }}
