name: Create and upload Conan package

on:
  workflow_call:
    inputs:
      repository:
        required: false
        default: ''
        type: string

      branch:
        required: false
        default: ''
        type: string

      private_data:
        required: false
        default: false
        type: boolean

      conan_recipe_root:
        required: false
        default: "."
        type: string

permissions:
  contents: read

jobs:
  conan-recipe-version:
    name: Calculate version numbers
    uses: ./.github/workflows/conan-recipe-version.yml
    with:
      repository: ${{ inputs.repository }}
      branch: ${{ inputs.branch }}
      conan_recipe_root: ${{ inputs.conan_recipe_root }}
      user: ultimaker
      channel: stable
      release: true

  conan-recipe-export:
    name: Upload package recipe
    needs: [ conan-recipe-version ]
    uses: ./.github/workflows/conan-recipe-export.yml
    with:
      repository: ${{ inputs.repository }}
      branch: ${{ inputs.branch }}
      version: ${{ needs.conan-recipe-version.outputs.version_base }}
      user: ultimaker
      channel: stable
      private_data: ${{ inputs.private_data }}
      conan_recipe_root: ${{ inputs.conan_recipe_root }}
    secrets: inherit
