name: Create and upload Conan package

on:
  workflow_call:
    inputs:
      private_data:
        required: false
        default: false
        type: boolean

      conan_extra_args:
        required: false
        default: ""
        type: string

      conan_recipe_root:
        required: false
        default: "."
        type: string

      platform_linux:
        required: false
        default: true
        type: boolean

      platform_windows:
        required: false
        default: true
        type: boolean

      platform_mac:
        required: false
        default: true
        type: boolean

      platform_wasm:
        required: false
        default: false
        type: boolean

      project_name:
        required: true
        type: string

permissions:
  contents: read

env:
  SENTRY_TOKEN: ${{ secrets.CURAENGINE_SENTRY_TOKEN }}

jobs:
# FIXME: Use main once merged
  conan-recipe-version:
    name: Calculate version numbers
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-11622_conan_v2
    with:
      project_name: ${{ inputs.project_name }}

# FIXME: Use main once merged
  conan-recipe-export:
    name: Upload package recipe
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@CURA-11622_conan_v2
    with:
      recipe_id_name: ${{ needs.conan-recipe-version.outputs.project_name }}
      recipe_id_version: ${{ needs.conan-recipe-version.outputs.recipe_semver_full }}
      recipe_id_user: ${{ needs.conan-recipe-version.outputs.user }}
      recipe_id_channel: ${{ needs.conan-recipe-version.outputs.channel }}
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit

# FIXME: Use main once merged
# FIXME: Re-enable if condition to build package only when required
  make-runners_list:
    name: Make the proper runners list
    uses: ultimaker/cura-workflows/.github/workflows/make-runners-list.yml@CURA-11622_conan_v2
    #if: ${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master' || needs.conan-recipe-version.outputs.is_release_branch == 'true')) }}
    with:
      platform_linux: ${{ inputs.platform_linux }}
      platform_windows: ${{ inputs.platform_windows }}
      platform_mac: ${{ inputs.platform_mac }}
      platform_wasm: ${{ inputs.platform_wasm }}

  conan-package-create:
    name: Create and upload package
    needs: [ conan-recipe-version, conan-recipe-export, make-runners_list ]
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: ${{ fromJson(needs.make-runners_list.outputs.matrix) }}

    steps:
# FIXME: use main once merged
      - name: Setup the build environment
        uses: ultimaker/cura-workflows/.github/actions/setup-build-environment@CURA-11622_conan_v2
        with:
          conan_user: ${{ secrets.CONAN_USER }}
          conan_password: ${{ secrets.CONAN_PASS }}
          install_system_dependencies: true

      - name: Create the Package (binaries)
        run: conan create ${{ inputs.conan_recipe_root }} --name ${{ needs.conan-recipe-version.outputs.project_name }} --version ${{ needs.conan-recipe-version.outputs.recipe_semver_full }} --user ${{ needs.conan-recipe-version.outputs.user }} --channel ${{ needs.conan-recipe-version.outputs.channel }} ${{ inputs.conan_extra_args }} --build=missing ${{ matrix.platform_conan_extra_args }}

# FIXME: use main once merged
      - name: Upload the Package
        uses: ultimaker/cura-workflows/.github/actions/upload-conan-package@CURA-11622_conan_v2
        with:
          package_name: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
          private_data: ${{ inputs.private_data }}
