name: Create and upload Conan package

on:
  workflow_call:
    inputs:
      repository:
        required: false
        default: ''
        type: string

      branch:
        required: false
        default: ''
        type: string

      private_data:
        required: false
        default: false
        type: boolean

      conan_recipe_root:
        required: false
        default: "."
        type: string

permissions:
  contents: read

jobs:
# FIXME: Use main once merged
  conan-recipe-version:
    name: Calculate version numbers
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-11622_conan_v2
    with:
      repository: ${{ inputs.repository }}
      branch: ${{ inputs.branch }}
      conan_recipe_root: ${{ inputs.conan_recipe_root }}
      release: true

# FIXME: Use main once merged
  conan-recipe-export:
    name: Upload package recipe
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@CURA-11622_conan_v2
    with:
      version: ${{ needs.conan-recipe-version.outputs.version_base }}
      user: ultimaker
      channel: stable
      package_version_full: ${{ needs.conan-recipe-version.outputs.package_version_full }}
      private_data: ${{ inputs.private_data }}
      conan_recipe_root: ${{ inputs.conan_recipe_root }}
    secrets: inherit
