name: All installers
run-name: ${{ inputs.cura_conan_version }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      cura_conan_version:
        required: true
        type: string
      conan_args:
        default: ''
        required: false
        type: string
      enterprise:
        default: false
        required: false
        type: boolean
      staging:
        default: false
        required: false
        type: boolean
      private_data:
        required: false
        default: false
        type: boolean


jobs:
  windows-installer:
# FIXME: Use main once merged
    name: Create Windows installer
    uses: ultimaker/cura-workflows/.github/workflows/cura-installer-windows.yml@CURA-11622_conan_v2
    with:
      cura_conan_version: ${{ inputs.cura_conan_version }}
      conan_args: ${{ inputs.conan_args }}
      enterprise: ${{ inputs.enterprise == 'true' }}
      staging: ${{ inputs.staging == 'true' }}
      operating_system: self-hosted-Windows-X64
      private_data: ${{ inputs.private_data }}
    secrets: inherit

# FIXME: Use main once merged
  linux-installer:
    name: Create Linux AppImage
    uses: ultimaker/cura-workflows/.github/workflows/cura-installer-linux.yml@CURA-11622_conan_v2
    with:
      cura_conan_version: ${{ inputs.cura_conan_version }}
      conan_args: ${{ inputs.conan_args }}
      enterprise: ${{ inputs.enterprise == 'true' }}
      staging: ${{ inputs.staging == 'true' }}
      operating_system: self-hosted-Ubuntu22-X64
      private_data: ${{ inputs.private_data }}
    secrets: inherit

  macos-installer:
# FIXME: Use main once merged
    name: Create MacOS-X64 packages
    uses: ultimaker/cura-workflows/.github/workflows/cura-installer-macos.yml@CURA-11622_conan_v2
    with:
      cura_conan_version: ${{ inputs.cura_conan_version }}
      conan_args: ${{ inputs.conan_args }}
      enterprise: ${{ inputs.enterprise == 'true' }}
      staging: ${{ inputs.staging == 'true' }}
      architecture: X64
      operating_system: self-hosted-X64
      private_data: ${{ inputs.private_data }}
    secrets: inherit

  macos-arm-installer:
# FIXME: Use main once merged
    name: Create MacOS-ARM64 packages
    uses: ultimaker/cura-workflows/.github/workflows/cura-installer-macos.yml@CURA-11622_conan_v2
    with:
      cura_conan_version: ${{ inputs.cura_conan_version }}
      conan_args: ${{ inputs.conan_args }}
      enterprise: ${{ inputs.enterprise == 'true' }}
      staging: ${{ inputs.staging == 'true' }}
      architecture: ARM64
      operating_system: self-hosted-ARM64
      private_data: ${{ inputs.private_data }}
    secrets: inherit
