name: Feature Freeze
run-name: Feature freeze Cura ${{ inputs.cura_version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      cura_version:
        description: 'Cura version major.minor, e.g. 5.7'
        required: true
        type: string

  push:
    branhes: [CURA-10769_automate_release_action]

jobs:
  feature-freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Create cura-binary-data release branch
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: Ultimaker
          repository_name: cura-binary-data
          new_branch_name: ${{ inputs.cura_version }}
          access_token: ${{ secrets.ACCESS_TOKEN}}
