name: Test release actions
run-name: Test

on:
  push

jobs:
  #test-feature-freeze:
    #uses: ultimaker/cura-workflows/.github/workflows/release-process_feature-freeze.yml@CURA-10769_automate_release_action
    #with:
      #cura_version: 255.123.42
    #secrets: inherit

  #test-release-candidate:
    #uses: ultimaker/cura-workflows/.github/workflows/release-process_release-candidate.yml@CURA-10769_automate_release_action
    #needs: [test-feature-freeze]
    #with:
      #cura_version: 255.123.42
    #secrets: inherit

  test-create-release-draft:
    name: Create the release draft
    runs-on: ubuntu-latest
    steps:
      - name: Get commit ID from tag
        id: get-commit-id
        uses: matheusraz/ref-sha@v1
        with:
          ref: 255.123.42-RC1

      - name: Create release
        uses: notpeelz/action-gh-create-release@v5.0.1
        with:
          repository: Ultimaker/Cura
          token: ${{ secrets.CURA_AUTORELEASE_PAT }}
          target: ${{ steps.get-commit-id.outputs.sha }}
          tag: 255.123.42
          strategy: replace
          title: UltiMaker Cura 255.123.42
          draft: true
