name: Feature Freeze
run-name: Feature freeze Cura ${{ inputs.cura_version }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      cura_version_major:
        description: 'Cura major version number, e.g. 5 for 5.7.2'
        required: true
        type: string
      cura_version_minor:
        description: 'Cura major version number, e.g. 7 for 5.7.2'
        required: true
        type: string
      cura_version_patch:
        description: 'Cura patch version number, e.g. 2 for 5.7.2'
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #repository: [Cura, Uranium, CuraEngine, cura-binary-data, fdm_materials]
        repository: [cura-binary-data]
    steps:
      - name: Create branch and update conan package version
        run: |
          git clone https://${{ secrets.CURA_AUTORELEASE_PAT }}@github.com/Ultimaker/${{ matrix.repository }}.git
          cd ${{ matrix.repository }}
          git checkout -b ${{ inputs.cura_version_major }}.${{ inputs.cura_version_minor }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          sed -i 's/version:.*/version: "${{ inputs.cura_version_major }}.${{ inputs.cura_version_minor }}.${{ inputs.cura_version_patch }}"/g' conandata.yml
          git add conandata.yml
          git commit -m ""
          git push origin `git branch --show-current`
