name: Feature Freeze
run-name: Feature freeze Cura ${{ inputs.cura_version }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      cura_version:
        description: 'Cura version major.minor, e.g. 5.7'
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [cura-binary-data, CuraEngine]
    steps:
      - name: Create cura-binary-data release branch
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: Ultimaker
          repository_name: ${{ matrix.repository }}
          new_branch_name: ${{ inputs.cura_version }}
          access_token: ${{ secrets.CURA_AUTORELEASE_PAT }}
