name: Test release actions
run-name: Test

on:
  push

jobs:
  #test-feature-freeze:
    #uses: ultimaker/cura-workflows/.github/workflows/release-process_feature-freeze.yml@CURA-10769_automate_release_action
    #with:
      #cura_version: 255.123.42
    #secrets: inherit

  #test-release-candidate:
    #uses: ultimaker/cura-workflows/.github/workflows/release-process_release-candidate.yml@CURA-10769_automate_release_action
    #needs: [test-feature-freeze]
    #with:
      #cura_version: 255.123.42
    #secrets: inherit

  test-create-release-draft:
    name: Create the release draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cura repo
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/Cura
          ref: 255.123.42
          token: ${{ secrets.CURA_AUTORELEASE_PAT }}

      - name: Checkout Cura-workflows repo
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/Cura-workflows
          path: Cura-workflows
          ref: CURA-10769_automate_release_action

      - name: Extract changelog
        run: python ./Cura-workflows/runner_scripts/extract_changelog.py --version 5.7.1 --changelog ./resources/texts/change_log.txt > formatted_changelog.txt

      - name: Create release
        uses: notpeelz/action-gh-create-release@v5.0.1
        with:
          repository: Ultimaker/Cura
          token: ${{ secrets.CURA_AUTORELEASE_PAT }}
          target: 41ccc9d5f43f2f4ad928b4aeef0a535fc7320b36
          tag: 255.123.42
          strategy: replace
          title: UltiMaker Cura 255.123.42
          draft: true
          body-source: file
          bosy: formatted_changelog.txt
